### ISSUE TITLE
WebInterface favicon bug

### ISSUE THREAD

**Issue by Sami32** [DigitalMediaServer/DigitalMediaServer#102]
On macOS:
```
DEBUG 2018-10-15 22:38:49.248 [pool-2-thread-2] root req /
ERROR 2018-10-15 22:38:49.248 [pool-2-thread-2] An error occurred while generating a HTTP response: No method or field with name 'favicons' on line 8
TRACE 2018-10-15 22:38:49.249 [pool-2-thread-2] 
com.samskivert.mustache.MustacheException$Context: No method or field with name 'favicons' on line 8
	at com.samskivert.mustache.Template.checkForMissing(Template.java:316)
	at com.samskivert.mustache.Template.getValue(Template.java:224)
	at com.samskivert.mustache.Template.getValueOrDefault(Template.java:269)
	at com.samskivert.mustache.Mustache$VariableSegment.execute(Mustache.java:802)
	at com.samskivert.mustache.Template.executeSegs(Template.java:150)
	at com.samskivert.mustache.Template.execute(Template.java:127)
	at com.samskivert.mustache.Template.execute(Template.java:118)
	at net.pms.remote.RemoteWeb$RemoteStartHandler.handle(RemoteWeb.java:435)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Sami32** [comment]
Invalid
