### ISSUE TITLE
Database exception while saving images informations

### ISSUE THREAD

**Issue by Sami32** [DigitalMediaServer/DigitalMediaServer#27]
```
TRACE 2017-11-13 16:50:07.125 [Library Scanner] Creating thumbnail for "capture_08132017_140129.jpg"
TRACE 2017-11-13 16:50:07.125 [Library Scanner] Converting input stream image source to SOURCE format and type DLNAThumbnail using the following parameters: ScaleType = MAX, Width = 320, Height = 320, PadToSize = False
DEBUG 2017-11-13 16:50:07.140 [Thread-40] Stopping UPNP Services...
TRACE 2017-11-13 16:50:07.375 [Library Scanner] Image conversion DLNA compliance check for JPEG_RES_320_231: The source image colors are compliant, format is non-compliant and resolution (1024 x 738) is non-compliant.
Failures:
  JPEG_RES_320_231 DLNA compliance failed with wrong resolution 1024 x 738 (limits are 320 x 231)
  JPEG DLNA compliance failed with too low JFIF version "1.01"
  JPEG DLNA compliance failed with non-typical Huffman tables
DEBUG 2017-11-13 16:50:07.406 [DMS Shutdown] Forcing shutdown of all active processes
INFO  2017-11-13 16:50:07.406 [DMS Shutdown] Stopping server on host 192.168.1.29 and port 5001...
TRACE 2017-11-13 16:50:07.671 [Library Scanner] Finished converting 1024Ã—738 JPEG image. Output image resolution: 320Ã—231, profile: JPEG_RES_320_231. Flags: Convert colors = False, Re-encode = True
ERROR 2017-11-13 16:50:07.687 [Library Scanner] Error updating cached thumbnail for "Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-196]": {}
TRACE 2017-11-13 16:50:07.687 [Library Scanner] 
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1484)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1469)
```

**Comment by Nadahar** [comment]
It's not really about the database, but away the unclean way the shutdown is done. I'm planning to refactor the whole shutdown system in the future, but it requires a lot of cleanup in thread handling before it's possible. Things are simply not in sync, so the database is shutdown before the library scanner has stopped.

**Comment by Sami32** [comment]
Ok. Thanks ;)
