### ISSUE TITLE
SetAVTransportURI failure

### ISSUE THREAD

**Issue by Sami32** [DigitalMediaServer/DigitalMediaServer#31]
See original log here:  http://www.universalmediaserver.com/forum/download/file.php?id=4251

It seem that the URI is not correctly formed at some step ?

```logtalk
<upnp:albumArtURI dlna:profileID="PNG_LRG" xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/">http://192.168.1.4:5001/get/29$Temp/thumbnail0000PNG_LRG_Arrow.S06E09.FASTSUB.VOSTFR.720p.HDTV.x264-ZT.WwW.Zone-Telechargement.Ws.mkv.png</upnp:albumArtURI><dc:date>2017-12-08T21:24:52</dc:date><upnp:class>object.item.videoItem</upnp:class></item>] to PCH-A500 (FF9D6500-8455-4D05-A481-B602C92852D0)[0]
ERROR 2017-12-09 22:30:11.921 [AWT-EventQueue-0] Failed to send action "SetAVTransportURI" to PCH-A500 (FF9D6500-8455-4D05-A481-B602C92852D0): Error: Unsupported format (HTTP response was: 500 Internal)
TRACE 2017-12-09 22:30:11.923 [AWT-EventQueue-0] 
org.fourthline.cling.model.action.ActionException: Unsupported format
	at org.fourthline.cling.transport.impl.SOAPActionProcessorImpl.readFaultElement(SOAPActionProcessorImpl.java:491)
	at org.fourthline.cling.transport.impl.SOAPActionProcessorImpl.readBodyFailure(SOAPActionProcessorImpl.java:212)
	at org.fourthline.cling.transport.impl.SOAPActionProcessorImpl.readBody(SOAPActionProcessorImpl.java:166)
	at org.fourthline.cling.protocol.sync.SendingAction.handleResponseFailure(SendingAction.java:155)
	at org.fourthline.cling.protocol.sync.SendingAction.invokeRemote(SendingAction.java:89)
	at org.fourthline.cling.protocol.sync.SendingAction.executeSync(SendingAction.java:63)
	at org.fourthline.cling.protocol.sync.SendingAction.executeSync(SendingAction.java:51)
	at org.fourthline.cling.protocol.SendingSync.execute(SendingSync.java:54)
	at org.fourthline.cling.protocol.SendingAsync.run(SendingAsync.java:54)
	at org.fourthline.cling.controlpoint.ActionCallback.run(ActionCallback.java:151)
	at net.pms.network.UPNPControl.send(UPNPControl.java:678)
	at net.pms.network.UPNPControl.setAVTransportURI(UPNPControl.java:859)
	at net.pms.network.UPNPHelper$Player.setURI(UPNPHelper.java:805)
	at net.pms.util.BasicPlayer$Logical.pressPlay(BasicPlayer.java:315)
	at net.pms.newgui.PlayerControlPanel$4.actionPerformed(PlayerControlPanel.java:124)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchTh
```

**Comment by Nadahar** [comment]
@Sami32 Both ```UPNPControl``` and ```UPnPHelper``` are so inaccurately implemented that I plan to replace them at some point. There are a lot of bugs and issues there. I'm more surprised when/if the renderer remote control stuff actually works.

**Comment by Sami32** [comment]
I tried to make some implementation in my fork, but as i'm not skilled it look more hack than other thing.

If you do that, that will also make much less Maven warning about unsafe code ;)

**Comment by Nadahar** [comment]
@Sami32 The warnings are very real 😉
