### ISSUE TITLE
Renderer Podcast parsing stream issue

### ISSUE THREAD

**Issue by Sami32** [DigitalMediaServer/DigitalMediaServer#49]
It come from UMS 7.0.1 but i suspect that it should be same in DMS.
```
DEBUG 2018-06-07 09:01:19.709 [HTTPv2 Request Worker 6] Recognized media renderer "[LG] webOS TV UH770V"
TRACE 2018-06-07 09:01:19.710 [HTTPv2 Request Worker 6] Received a browse request from [LG] webOS TV UH770V [LG WebOS TV] (192.168.1.2:44542):

POST /upnp/control/content_directory HTTP/1.1

HEADER:
  SOAPAction: "urn:schemas-upnp-org:service:ContentDirectory:1#Browse"
  DLNADeviceName.lge.com: %5bLG%5d%20webOS%20TV%20UH770V
  User-Agent: Linux/3.10.19-p.43.dharug.k2l.4 UPnP/1.0 LGE WebOS TV LGE_DLNA_SDK/1.6.0/05.30.03 DLNADOC/1.50
  Host: 192.168.1.7:5001
  Content-Length: 676
  Content-Type: text/xml; charset="utf-8"

CONTENT:
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
    <s:Body>
        <u:Browse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1">
            <ObjectID>71</ObjectID>
            <BrowseFlag>BrowseDirectChildren</BrowseFlag>
            <Filter>res@resolution,res@nrAudioChannels,res@sampleFrequency,res@bitrate,dc:creator,res@dlna:cleartextSize,dc:date,upnp:genre,res,res@duration,res@size,upnp:albumArtURI,upnp:originalTrackNumber,upnp:album,upnp:artist,upnp:author</Filter>
            <StartingIndex>0</StartingIndex>
            <RequestedCount>30</RequestedCount>
            <SortCriteria/>
        </u:Browse>
    </s:Body>
</s:Envelope>

DEBUG 2018-06-07 09:01:19.712 [DLNAResource resolver thread 11-1] Retrieving http://podcasts.engadget.com/rss.xml
ERROR 2018-06-07 09:01:19.778 [DLNAResource resolver thread 11-1] Error in parsing stream: http://podcasts.engadget.com/rss.xml
java.net.UnknownHostException: podcasts.engadget.com
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at net.pms.network.HTTPResource.downloadAndSendBinary(HTTPResource.java:208)
	at net.pms.network.HTTPResource.downloadAndSendBinary(HTTPResource.java:182)
	at net.pms.dlna.Feed.parse(Feed.java:109)
	at net.pms.dlna.Feed.resolveOnce(Feed.java:94)
	at net.pms.dlna.DLNAResource.resolve(DLNAResource.java:1612)
	at net.pms.dlna.DLNAResource.syncResolve(DLNAResource.java:1592)
	at net.pms.dlna.DLNAResource.run(DLNAResource.java:1389)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
TRACE 2018-06-07 09:01:19.779 [HTTPv2 Request Worker 6] End of analysis for Podcasts
TRACE 2018-06-07 09:01:19.781 [HTTPv2 Request Worker 6] Response sent to [LG] webOS TV UH770V [LG WebOS TV]:

HEADER:
  HTTP/1.1 200 OK
  Content-Type: text/xml; charset="utf-8"
  Server: Windows_10-amd64-10.0, UPnP/1.0 DLNADOC/1.50, UMS/7.1.0-SNAPSHOT
  Content-Length: 2604

CONTENT:
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
    <s:Body>
```

**Comment by Sami32** [comment]
```
ERROR 2018-06-05 19:53:31.431 [DLNAResource resolver thread 14-1] Error in parsing stream: http://feeds.theonion.com/onionnewsnetwork
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: The element type "meta" must be terminated by the matching end-tag "</meta>".
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:198)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:123)
	at net.pms.dlna.Feed.parse(Feed.java:111)
	at net.pms.dlna.Feed.resolveOnce(Feed.java:94)
	at net.pms.dlna.DLNAResource.resolve(DLNAResource.java:1613)
	at net.pms.dlna.DLNAResource.syncResolve(DLNAResource.java:1593)
	at net.pms.dlna.DLNAResource.run(DLNAResource.java:1390)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: The element type "meta" must be terminated by the matching end-tag "</meta>".
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:194)
	... 9 common frames omitted
Caused by: org.xml.sax.SAXParseException: The element type "meta" must be terminated by the matching end-tag "</meta>".
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 11 common frames omitted
```

**Comment by Sami32** [comment]
OK, i didn't tested it.
