### ISSUE TITLE
ArithmeticException in the Timer

### ISSUE THREAD

**Issue by Sami32** [DigitalMediaServer/DigitalMediaServer#50]
http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=12515&start=10
```
INFO  2018-06-05 19:55:17.782 [ffmpeg64.exe-55-Timer] Exception in thread "ffmpeg64.exe-55-Timer" java.lang.ArithmeticException: / by zero
INFO  2018-06-05 19:55:17.782 [ffmpeg64.exe-55-Timer] 	at net.pms.newgui.StatusTab$RendererItem.actionPerformed(StatusTab.java:99)
INFO  2018-06-05 19:55:17.783 [ffmpeg64.exe-55-Timer] 	at net.pms.util.BasicPlayer$Minimal.alert(BasicPlayer.java:150)
INFO  2018-06-05 19:55:17.783 [ffmpeg64.exe-55-Timer] 	at net.pms.util.BasicPlayer$Logical.alert(BasicPlayer.java:351)
INFO  2018-06-05 19:55:17.783 [ffmpeg64.exe-55-Timer] 	at net.pms.util.BasicPlayer$Minimal.reset(BasicPlayer.java:117)
INFO  2018-06-05 19:55:17.783 [ffmpeg64.exe-55-Timer] 	at net.pms.util.BasicPlayer$Minimal.<init>(BasicPlayer.java:103)
INFO  2018-06-05 19:55:17.783 [ffmpeg64.exe-55-Timer] 	at net.pms.util.BasicPlayer$Logical.<init>(BasicPlayer.java:262)
INFO  2018-06-05 19:55:17.783 [ffmpeg64.exe-55-Timer] 	at net.pms.network.UPNPHelper$Player.<init>(UPNPHelper.java:787)
INFO  2018-06-05 19:55:17.783 [ffmpeg64.exe-55-Timer] 	at net.pms.configuration.RendererConfiguration.getPlayer(RendererConfiguration.java:1585)
INFO  2018-06-05 19:55:17.783 [ffmpeg64.exe-55-Timer] 	at net.pms.configuration.RendererConfiguration.setBuffer(RendererConfiguration.java:2737)
INFO  2018-06-05 19:55:17.783 [ffmpeg64.exe-55-Timer] 	at net.pms.io.BufferedOutputFileImpl$1.run(BufferedOutputFileImpl.java:815)
INFO  2018-06-05 19:55:17.783 [ffmpeg64.exe-55-Timer] 	at java.util.TimerThread.mainLoop(Unknown Source)
INFO  2018-06-05 19:55:17.783 [ffmpeg64.exe-55-Timer] 	at java.util.TimerThread.run(Unknown Source)
```

**Comment by Sami32** [comment]
```
`DEBUG 2018-06-05 19:53:08.395 [cling-7] New renderer found: "[LG] webOS TV UH770V" with dlna details: {friendlyName=[LG] webOS TV UH770V, address=192.168.1.5, udn=uuid:ffd654e5-f51a-2c85-05bc-5ca6267fe8f4, manufacturer=LG Electronics, modelName=LG Smart TV, modelNumber=60UH770V-ZA, modelDescription=, manufacturerURL=http://www.lge.com, modelURL=http://www.lge.com}
DEBUG 2018-06-05 19:53:08.395 [cling-7] Adding device: urn:schemas-upnp-org:device:Basic:1 (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:ffd654e5-f51a-2c85-05bc-5ca6267fe8f4, Descriptor: http://192.168.1.5:1170/, Root: true
DEBUG 2018-06-05 19:53:08.395 [cling-7] Subscribing to webos-second-screen-3000-3001 service on [LG] webOS TV UH770V
TRACE 2018-06-05 19:53:08.397 [cling-10] Matched media renderer "[LG] webOS TV UH770V" based on address 192.168.1.5
INFO  2018-06-05 19:53:08.398 [cling-7] Exception in thread "cling-7" java.lang.ArithmeticException: / by zero
INFO  2018-06-05 19:53:08.398 [cling-7] 	at net.pms.newgui.StatusTab$RendererItem.actionPerformed(StatusTab.java:99)
INFO  2018-06-05 19:53:08.398 [cling-7] 	at net.pms.util.BasicPlayer$Minimal.alert(BasicPlayer.java:150)
INFO  2018-06-05 19:53:08.398 [cling-7] 	at net.pms.util.BasicPlayer$Minimal.reset(BasicPlayer.java:117)
INFO  2018-06-05 19:53:08.398 [cling-7] 	at net.pms.util.BasicPlayer$Minimal.<init>(BasicPlayer.java:103)
INFO  2018-06-05 19:53:08.398 [cling-7] 	at net.pms.configuration.RendererConfiguration$PlaybackTimer.<init>(RendererConfiguration.java:2752)
INFO  2018-06-05 19:53:08.398 [cling-7] 	at net.pms.configuration.RendererConfiguration.getPlayer(RendererConfiguration.java:1585)
INFO  2018-06-05 19:53:08.398 [cling-7] 	at net.pms.network.UPNPHelper.rendererReady(UPNPHelper.java:756)
INFO  2018-06-05 19:53:08.399 [cling-7] 	at net.pms.network.UPNPControl.addRenderer(UPNPControl.java:489)
INFO  2018-06-05 19:53:08.399 [cling-7] 	at net.pms.network.UPNPControl$2.remoteDeviceAdded(UPNPControl.java:307)
INFO  2018-06-05 19:53:08.399 [cling-7] 	at org.fourthline.cling.registry.RemoteItems$1.run(RemoteItems.java:111)
INFO  2018-06-05 19:53:08.399 [cling-7] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
INFO  2018-06-05 19:53:08.399 [cling-7] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
INFO  2018-06-05 19:53:08.399 [cling-7] 	at java.lang.Thread.run(Unknown Source)
DEBUG 2018-06-05 19:53:08.399 [cling-10] Matched media renderer "LG WebOS TV" based on dlna details "[LG] webOS TV UH770V 192.168.1.5 uuid:5a95aebb-3c08-673f-29fe-c769dc195e0a LG Electronics. LG TV 1.0 LG WebOSTV DMRplus http://www.lge.com "
```
