### ISSUE TITLE
java.io.InvalidClassException: net.pms.image.ImageInfo

### ISSUE THREAD

**Issue by Sami32** [DigitalMediaServer/DigitalMediaServer#84]
>TRACE 2018-09-14 21:01:03.125 [HTTPv2 Request Worker 1] Matched format FLAC to "F:\_DEVELOPPEMENT_TOOLS\!MEDIA_TEST_FILES\AUDIO\FLAC\2L-056_03_stereo-44kHz-16b.flac"
DEBUG 2018-09-14 21:01:03.203 [HTTPv2 Request Worker 1] Cached information about 2L-056_03_stereo-44kHz-16b.flac seems to be from a previous version, reparsing information
TRACE 2018-09-14 21:01:03.218 [HTTPv2 Request Worker 1] 
java.io.InvalidClassException: net.pms.image.ImageInfo; local class incompatible: stream classdesc serialVersionUID = 8947090782856389500, local class serialVersionUID = 4247040093720562338
	at java.io.ObjectStreamClass.initNonProxy(Unknown Source)
	at java.io.ObjectInputStream.readNonProxyDesc(Unknown Source)
	at java.io.ObjectInputStream.readClassDesc(Unknown Source)
	at java.io.ObjectInputStream.readNonProxyDesc(Unknown Source)
	at java.io.ObjectInputStream.readClassDesc(Unknown Source)
	at java.io.ObjectInputStream.readNonProxyDesc(Unknown Source)
	at java.io.ObjectInputStream.readClassDesc(Unknown Source)
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
	at java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.io.ObjectInputStream.defaultReadFields(Unknown Source)
	at java.io.ObjectInputStream.readSerialData(Unknown Source)
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
	at java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.io.ObjectInputStream.readObject(Unknown Source)
	at org.h2.util.JdbcUtils.deserialize(JdbcUtils.java:420)
	at org.h2.jdbc.JdbcConnection.convertToDefaultObject(JdbcConnection.java:2023)
	at org.h2.jdbc.JdbcResultSet.getObject(JdbcResultSet.java:534)
	at net.pms.dlna.DLNAMediaDatabase.getData(DLNAMediaDatabase.java:363)
	at net.pms.dlna.RealFile.resolve(RealFile.java:185)
	at net.pms.dlna.DLNAResource.syncResolve(DLNAResource.java:1511)
	at net.pms.dlna.DLNAResource.run(DLNAResource.java:1346)
	at net.pms.dlna.RealFile.isValid(RealFile.java:70)
	at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:644)
	at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:608)
	at net.pms.dlna.MapFile.manageFile(MapFile.java:311)
	at net.pms.dlna.MapFile.analyzeChildren(MapFile.java:364)
	at net.pms.dlna.DLNAResource.discoverWithRenderer(DLNAResource.java:1310)
	at net.pms.dlna.DLNAResource.getDLNAResources(DLNAResource.java:1225)
	at net.pms.network.RequestV2.answer(RequestV2.java:804)
	at net.pms.network.RequestHandlerV2.writeResponse(RequestHandlerV2.java:392)
	at net.pms.network.RequestHandlerV2.messageReceived(RequestHandlerV2.java:266)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:485)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Sami32** [comment]
Did i said that it was tested with the CueLib PR ;)

**Comment by Nadahar** [comment]
Hehe

I don't quite understand what it means, but can I guess that there's some embedded image in that file?

**Comment by Nadahar** [comment]
Ah, no, forget it.

This isn't a real error, it's just you running different versions on the same database.

**Comment by Sami32** [comment]
http://ge.tt/78ulber2

**Comment by Sami32** [comment]
Hehe ok.
Good then ;)

**Comment by Sami32** [comment]
Yes they have cover art

**Comment by Nadahar** [comment]
Logging tweaked to not log the stack trace when this happens in 40727644c5c068e28eb05bb90d2133754bf6a617. I know it bothers you :stuck_out_tongue_closed_eyes:
